### ISSUE TITLE
Use QUDT ontology for units, quantities and etc.

### ISSUE THREAD

**Issue by KMax** [semiotproject/wot-semdesc-helper#10]
Use the QUDT ontology (http://www.qudt.org/) to represent the units of measurement.

**Comment by soylent-grin** [comment]
QUDT ontology contains about 150 quantities and units. Should we make user to be available to select all of them? If so, should we construct the list of available units dynamicly via SPARQL query to some endpoint?

**Comment by KMax** [comment]
I think, we will need to upload the ontology to our triplestore, because usually ontologies are just files, so it's not possible to query them.

**Comment by soylent-grin** [comment]
So, the answer is - yes, query endpoint for the list of available units and quantities and construct dropdown dynamically - correct?

**Comment by KMax** [comment]
Yeap
