### ISSUE TITLE
Implement Instance View

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/wot-semdesc-helper#15]
We should have separate tab (e. g. 'Instance'), where each user, even unauthorized, should be able to:
- select one class from the list
- prompt additional info about particular device (location, etc..?)
- download the result description as a file.
  Target format is JSON-LD, maybe other will be available too

**Comment by soylent-grin** [comment]
Done.
For each device model, user can create instance templates for this model; templates consist of device description template and N observation templates, where N is the amount of sensors; user can edit placeholders in templates (set of placeholders in under discussion) and download each template as a single file.
@KMax please verify the workflow with templates on http://semdesc.semiot.ru/.

**Comment by KMax** [comment]
Looks like the button to create an instance doesn't work. Should it be like a link or button? I see just a text.

P.S. I create my own model from scratch.

**Comment by soylent-grin** [comment]
Ok, for some reason Chrome (and Midori) support non-standart HTML (and Firefox not): http://stackoverflow.com/a/17253457. Fixed.
BTW you should re-create model again now due https://github.com/semiotproject/wot-semdesc-helper/issues/29

**Comment by soylent-grin** [comment]
Ready for first prototype.
