### ISSUE TITLE
Use Provenance ontology to store creator of class

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/wot-semdesc-helper#16]
http://www.w3.org/TR/prov-o/

**Comment by KMax** [comment]
Take a look at Example 1 from #11 issue, there are few triples which use PROV ontology to describe the relationship between the generated class and the creator.

So in this example is shown how to record the email and name of the creator. But if it's needed to record something else, then we just can reuse something from other ontologies, like FOAF.

**Comment by KMax** [comment]
@garayzuev What do we want to know about the creator? In #11 example, only the name and email address are used, is it enough?

**Comment by garayzuev** [comment]
@KMax , I think, it's enough

**Comment by soylent-grin** [comment]
If so, note that `[UUID-creator]` should be not a random UUID, but a GitHub user's URI - to make available mapping with the current user.

**Comment by KMax** [comment]
Good point @soylent-grin! Formally, it's incorrect to use Github user's URL, because the URL refers to a web page, but not a resource representing a user, but I think it's acceptable.

**Comment by soylent-grin** [comment]
We also could store some identifier (id, login or GitHub URI) in triple itself - any variant is acceptable for me. @garayzuev, choose one of the mentioned above variants and verify it in this thread after implementing.

**Comment by KMax** [comment]
To be safe, I suggest the following option:

```
:[UUID-creator] a prov:Agent, prov:Person, foaf:Person ;
        foaf:givenName ""^^xsd:string ;
        foaf:mbox <mailto:..> ;
        foaf:homepage <http://github.com/UserName> .

<http://github.com/UserName> a foaf:PersonalProfileDocument ;
        foaf:maker :[UUID-creator] ;
        foaf:primaryTopic :[UUID-creator] .
```

Then we're formally correct.

**Comment by soylent-grin** [comment]
:+1:
