### ISSUE TITLE
Switch to 'application/turtle' 

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/wot-semdesc-helper#23]
Now we generate and work with RDF in Turtle format - not JSON-LD. API should be corrected by this issue.

**Comment by soylent-grin** [comment]
BTW, on the `/#/model/new/` page you can fill form fields and test your API - on save, a `POST` request to `/api/model/`(note slash on the end) with ttl body is sent, so you may need also to change API path.

**Comment by garayzuev** [comment]
@soylent-grin, did you mean `text/turtle'?

**Comment by soylent-grin** [comment]
Yep.
Did you check query from UI - new class is creating?

**Comment by garayzuev** [comment]
Nope, you should change content-type from `application/turtle` to `text/turtle` at frontend

**Comment by soylent-grin** [comment]
done
