### ISSUE TITLE
Extract Fuseki volume out of the Docker container

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/wot-semdesc-helper#29]
Or after each deploy all created models are gone.

**Comment by KMax** [comment]
There is a problem with reasoning on named graphs, so we have to create one dataset for storing ontologies and mappings which supports reasoning and another dataset for storing models in named graphs, but without reasoning.

@soylent-grin Do we need reasoning for the named graphs?

The discussion in the mailing list -> http://mail-archives.apache.org/mod_mbox/jena-users/201603.mbox/%3CCA%2BRbaMAQjUHqom_9FmB5qoVSDE__FNw1oVdCF_TKtizwuV5SLg%40mail.gmail.com%3E

**Comment by KMax** [comment]
I did a commit with the changes. So from now:
- `http://.../default/query` should be used to query the ontologies and mappings,
- `http://.../private/query` should be used to query the models (classes).

**Comment by soylent-grin** [comment]
> Do we need reasoning for the named graphs?

I guess not, we work with entire amount of model graphs' triples as-is.
