### ISSUE TITLE
Add authorization and RBAC support

### ISSUE THREAD

**Issue by soylent-grin** [semiotproject/wot-semdesc-helper#8]
We need a simple backend service with DB to allow authentication to web app through OAuth (e. g. GitHub?). Each user should have access to only his own set of descriptions.

**Comment by KMax** [comment]
Scenarios:
- any user (even anonymous) is able to see the list of class in the catalog,
- only the creater of the class can (re)edit/remove it,
- only authenticated user can save a new class to the catalog,
- any authenticated user can create an instance from any class from the catalog.
